### ISSUE TITLE
Does not work and breaks my game

### ISSUE THREAD

**Issue by eloris45** [Vek17/WrathMods-MythicSpellbookTweaks#2]
Hi after enabling the mod it seems like the mythic spell DCs got fixed, it does not change when the casting ability score changes (and it does not change the ability score for DC calculation as intended). The problem persists even after I deleting the mod.
Please fix this.

**Comment by eloris45** [comment]
OK I figured out that the casting ability for mythic spells is actually your mythic rank. But this mod still does not successfully change your casting ability.

**Comment by Vek17** [comment]
This has been fixed in 3.1.0, had some old beta stuff floating around.
